=== LaozpGZ/SimpleFlow-monorepo/apps/token-list/test/schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "pancakeswap",
  "title": "PancakeSwap Token List",
  "description": "Schema for lists of tokens compatible with the PancakeSwap Interface, including Uniswap standard and PancakeSwap Aptos",
  "definitions": {
    "Version": {
      "type": "object",
      "description": "The version of the list, used in change detection",
      "examples": [
        {
          "major": 1,
          "minor": 0,
          "patch": 0
        }
      ],
      "additionalProperties": false,
      "properties": {
        "major": {
          "type": "integer",
          "description": "The major version of the list. Must be incremented when tokens are removed from the list or token addresses are changed.",
          "minimum": 0,
          "examples": [1, 2]
        },
        "minor": {
          "type": "integer",
          "description": "The minor version of the list. Must be incremented when tokens are added to the list.",
          "minimum": 0,
          "examples": [0, 1]
        },
        "patch": {
          "type": "integer",
          "description": "The patch version of the list. Must be incremented for any changes to the list.",
          "minimum": 0,
          "examples": [0, 1]
        }
      },
      "required": ["major", "minor", "patch"]
    },
    "TagIdentifier": {
      "type": "string",
      "description": "The unique identifier of a tag",
      "minLength": 1,
      "maxLength": 10,
      "pattern": "^[\\w]+$",
      "examples": ["compound", "stablecoin"]
    },
    "ExtensionIdentifier": {
      "type": "string",
      "description": "The name of a token extension property",
      "minLength": 1,
      "maxLength": 40,
      "pattern": "^[\\w]+$",
      "examples": ["color", "is_fee_on_transfer", "aliases"]
    },
    "ExtensionMap": {
      "type": "object",
      "description": "An object containing any arbitrary or vendor-specific token metadata",
      "maxProperties": 10,
      "propertyNames": {
        "$ref": "#/definitions/ExtensionIdentifier"
      },
      "additionalProperties": {
        "$ref": "#/definitions/ExtensionValue"
      },
      "examples": [
        {
          "color": "#000000",
          "is_verified_by_me": true
        },
        {
          "x-bridged-addresses-by-chain": {
            "1": {
              "bridgeAddress": "0x4200000000000000000000000000000000000010",
              "tokenAddress": "0x4200000000000000000000000000000000000010"
            }
          }
        }
      ]
    },
    "ExtensionPrimitiveValue": {
      "anyOf": [
        {
          "type": "string",
          "minLength": 1,
          "maxLength": 42,
          "examples": ["#00000"]
        },
        {
          "type": "boolean",
          "examples": [true]
        },
        {
          "type": "number",
          "examples": [15]
        },
        {
          "type": "null"
        }
      ]
    },
    "ExtensionValue": {
      "anyOf": [
        {
          "$ref": "#/definitions/ExtensionPrimitiveValue"
        },
        {
          "type": "object",
          "maxProperties": 10,
          "propertyNames": {
            "$ref": "#/definitions/ExtensionIdentifier"
          },
          "additionalProperties": {
            "$ref": "#/definitions/ExtensionValueInner0"
          }
        }
      ]
    },
    "ExtensionValueInner0": {
      "anyOf": [
        {
          "$ref": "#/definitions/ExtensionPrimitiveValue"
        },
        {
          "type": "object",
          "maxProperties": 10,
          "propertyNames": {
            "$ref": "#/definitions/ExtensionIdentifier"
          },
          "additionalProperties": {
            "$ref": "#/definitions/ExtensionValueInner1"
          }
        }
      ]
    },
    "ExtensionValueInner1": {
      "anyOf": [
        {
          "$ref": "#/definitions/ExtensionPrimitiveValue"
        }
      ]
    },
    "TagDefinition": {
      "type": "object",
      "description": "Definition of a tag that can be associated with a token via its identifier",
      "additionalProperties": false,
      "properties": {
        "name": {
          "type": "string",
          "description": "The name of the tag",
          "pattern": "^[ \\w]+$",
          "minLength": 1,
          "maxLength": 20
        },
        "description": {
          "type": "string",
          "description": "A user-friendly description of the tag",
          "pattern": "^[ \\w\\.,:]+$",
          "minLength": 1,
          "maxLength": 200
        }
      },
      "required": ["name", "description"],
      "examples": [
        {
          "name": "Stablecoin",
          "description": "A token with value pegged to another asset"
        }
      ]
    },
    "TokenInfo": {
      "type": "object",
      "description": "Metadata for a single token in a token list",
      "additionalProperties": false,
      "properties": {
        "chainId": {
          "type": "integer",
          "description": "The chain ID of the Ethereum network where this token is deployed",
          "minimum": 1,
          "examples": [1, 42]
        },
        "address": {
          "type": "string",
          "description": "The checksummed address of the token on the specified chain ID",
          "pattern": "^0x[a-fA-F0-9]{40}$",
          "examples": ["0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48"]
        },
        "decimals": {
          "type": "integer",
          "description": "The number of decimals for the token balance",
          "minimum": 0,
          "maximum": 255,
          "examples": [18]
        },
        "name": {
          "type": "string",
          "description": "The name of the token",
          "minLength": 1,
          "maxLength": 40,
          "pattern": "^[ \\w.'+\\-%/À-ÖØ-öø-ÿ:&\\[\\]\\(\\)]+$",
          "examples": ["USD Coin"]
        },
        "symbol": {
          "type": "string",
          "description": "The symbol for the token; must be alphanumeric",
          "pattern": "^[a-zA-Z0-9+\\-%/$.\\s]+$",
          "minLength": 1,
          "maxLength": 20,
          "examples": ["USDC"]
        },
        "logoURI": {
          "type": "string",
          "description": "A URI to the token logo asset; if not set, interface will attempt to find a logo based on the token address; suggest SVG or PNG of size 64x64",
          "format": "uri",
          "examples": ["ipfs://QmXfzKRvjZz3u5JRgC4v5mGVbm9ahrUiB4DgzHBsnWbTMM"]
        },
        "tags": {
          "type": "array",
          "description": "An array of tag identifiers associated with the token; tags are defined at the list level",
          "items": {
            "$ref": "#/definitions/TagIdentifier"
          },
          "maxItems": 10,
          "examples": ["stablecoin", "compound"]
        },
        "extensions": {
          "$ref": "#/definitions/ExtensionMap"
        }
      },
      "required": ["chainId", "address", "decimals", "name", "symbol"]
    },
    "AptosTokenInfo": {
      "type": "object",
      "description": "Metadata for a single token in a token list",
      "additionalProperties": false,
      "properties": {
        "chainId": {
          "type": "integer",
          "description": "The chain ID of the Aptos network where this token is deployed, 0 is devent",
          "minimum": 0,
          "examples": [1, 42]
        },
        "address": {
          "type": "string",
          "description": "The address of the coin on the specified chain ID",
          "examples": ["0x1::aptos_coin::AptosCoin"]
        },
        "decimals": {
          "type": "integer",
          "description": "The number of decimals for the token balance",
          "minimum": 0,
          "maximum": 255,
          "examples": [18]
        },
        "name": {
          "type": "string",
          "description": "The name of the token",
          "minLength": 1,
          "maxLength": 40,
          "pattern": "^[ \\w.'+\\-%/À-ÖØ-öø-ÿ:&\\[\\]\\(\\)]+$",
          "examples": ["USD Coin"]
        },
        "symbol": {
          "type": "string",
          "description": "The symbol for the token; must be alphanumeric",
          "pattern": "^[a-zA-Z0-9+\\-%/$.]+$",
          "minLength": 1,
          "maxLength": 20,
          "examples": ["USDC"]
        },
        "logoURI": {
          "type": "string",
          "description": "A URI to the token logo asset; if not set, interface will attempt to find a logo based on the token address; suggest SVG or PNG of size 64x64",
          "format": "uri",
          "examples": ["ipfs://QmXfzKRvjZz3u5JRgC4v5mGVbm9ahrUiB4DgzHBsnWbTMM"]
        },
        "tags": {
          "type": "array",
          "description": "An array of tag identifiers associated with the token; tags are defined at the list level",
          "items": {
            "$ref": "#/definitions/TagIdentifier"
          },
          "maxItems": 10,
          "examples": ["stablecoin", "compound"]
        },
        "extensions": {
          "$ref": "#/definitions/ExtensionMap"
        }
      },
      "required": ["chainId", "address", "decimals", "name", "symbol"]
    },
    "SolanaTokenInfo": {
      "type": "object",
      "description": "Metadata for a single token in a token list",
      "additionalProperties": false,
      "properties": {
        "chainId": {
          "type": "integer",
          "description": "The chain ID of the Solana network where this token is deployed",
          "minimum": 0,
          "examples": [101]
        },
        "address": {
          "type": "string",
          "description": "The address of the coin on the specified chain ID",
          "pattern": "^[1-9A-HJ-NP-Za-km-z]{32,44}$",
          "examples": ["So11111111111111111111111111111111111111112"]
        },
        "programId": {
          "type": "string",
          "description": "The program ID of the token on the specified chain ID",
          "pattern": "^[1-9A-HJ-NP-Za-km-z]{32,44}$",
          "examples": ["TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"]
        },
        "decimals": {
          "type": "integer",
          "description": "The number of decimals for the token balance",
          "minimum": 0,
          "maximum": 255,
          "examples": [18]
        },
        "name": {
          "type": "string",
          "description": "The name of the token",
          "minLength": 1,
          "maxLength": 40,
          "pattern": "^[ \\w'+\\-%/À-ÖØ-öø-ÿ:&\\[\\]\\(\\)\\$]+$",
          "examples": ["USD Coin"]
        },
        "symbol": {
          "type": "string",
          "description": "The symbol for the token; must be alphanumeric",
          "pattern": "^[a-zA-Z0-9+\\-%/$_]+$",
          "minLength": 1,
          "maxLength": 20,
          "examples": ["USDC"]
        },
        "logoURI": {
          "type": "string",
          "description": "A URI to the token logo asset; if not set, interface will attempt to find a logo based on the token address; suggest SVG or PNG of size 64x64",
          "format": "uri",
          "examples": ["ipfs://QmXfzKRvjZz3u5JRgC4v5mGVbm9ahrUiB4DgzHBsnWbTMM"]
        },
        "tags": {
          "type": "array",
          "description": "An array of tag identifiers associated with the token; tags are defined at the list level",
          "items": {
            "$ref": "#/definitions/TagIdentifier"
          },
          "maxItems": 10,
          "examples": ["stablecoin", "compound"]
        },
        "extensions": {
          "$ref": "#/definitions/ExtensionMap"
        }
      },
      "required": ["chainId", "address", "programId", "decimals", "name", "symbol"]
    }
  },
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "name": {
      "type": "string",
      "description": "The name of the token list",
      "minLength": 1,
      "maxLength": 30,
      "pattern": "^[\\w ]+$",
      "examples": ["My Token List"]
    },
    "timestamp": {
      "type": "string",
      "format": "date-time",
      "description": "The timestamp of this list version; i.e. when this immutable version of the list was created"
    },
    "schema": {
      "type": "string"
    },
    "version": {
      "$ref": "#/definitions/Version"
    },
    "tokens": {
      "type": "array",
      "description": "The list of tokens included in the list",
      "minItems": 1,
      "maxItems": 10000
    },
    "keywords": {
      "type": "array",
      "description": "Keywords associated with the contents of the list; may be used in list discoverability",
      "items": {
        "type": "string",
        "description": "A keyword to describe the contents of the list",
        "minLength": 1,
        "maxLength": 20,
        "pattern": "^[\\w ]+$",
        "examples": ["compound", "lending", "personal tokens"]
      },
      "maxItems": 20,
      "uniqueItems": true
    },
    "tags": {
      "type": "object",
      "description": "A mapping of tag identifiers to their name and description",
      "propertyNames": {
        "$ref": "#/definitions/TagIdentifier"
      },
      "additionalProperties": {
        "$ref": "#/definitions/TagDefinition"
      },
      "maxProperties": 20,
      "examples": [
        {
          "stablecoin": {
            "name": "Stablecoin",
            "description": "A token with value pegged to another asset"
          }
        }
      ]
    },
    "logoURI": {
      "type": "string",
      "description": "A URI for the logo of the token list; prefer SVG or PNG of size 256x256",
      "format": "uri",
      "examples": ["ipfs://QmXfzKRvjZz3u5JRgC4v5mGVbm9ahrUiB4DgzHBsnWbTMM"]
    }
  },
  "allOf": [
    {
      "if": {
        "properties": {
          "schema": {
            "const": "aptos"
          }
        },
        "required": ["name", "timestamp", "version", "tokens", "schema"]
      },
      "then": {
        "properties": {
          "tokens": {
            "items": {
              "$ref": "#/definitions/AptosTokenInfo"
            },
            "type": "array",
            "description": "The list of tokens included in the list",
            "minItems": 1,
            "maxItems": 10000
          }
        }
      }
    },
    {
      "if": {
        "properties": {
          "schema": {
            "const": "solana"
          }
        },
        "required": ["name", "timestamp", "version", "tokens", "schema"]
      },
      "then": {
        "properties": {
          "tokens": {
            "items": {
              "$ref": "#/definitions/SolanaTokenInfo"
            },
            "type": "array",
            "description": "The list of tokens included in the list",
            "minItems": 1,
            "maxItems": 10000
          }
        }
      }
    },
    {
      "else": {
        "properties": {
          "tokens": {
            "items": {
              "$ref": "#/definitions/TokenInfo"
            },
            "type": "array",
            "description": "The list of tokens included in the list",
            "minItems": 1,
            "maxItems": 10000
          }
        }
      }
    }
  ],
  "required": ["name", "timestamp", "version", "tokens"]
}

=== LaozpGZ/SimpleFlow-monorepo/apps/token-list/lists/pancakeswap-zksync-default.json
{
  "name": "PancakeSwap Zksync Default",
  "timestamp": "2024-06-21T13:12:18.339Z",
  "version": {
    "major": 1,
    "minor": 0,
    "patch": 24
  },
  "logoURI": "https://pancakeswap.finance/logo.png",
  "keywords": ["pancakeswap", "default", "zksync"],
  "tokens": [
    {
      "name": "PancakeSwap Token",
      "symbol": "CAKE",
      "address": "0x3A287a06c66f9E95a56327185cA2BDF5f031cEcD",
      "chainId": 324,
      "decimals": 18,
      "logoURI": "https://tokens.pancakeswap.finance/images/zksync/0x3A287a06c66f9E95a56327185cA2BDF5f031cEcD.png"
    },
    {
      "name": "Wrapped Ether",
      "symbol": "WETH",
      "address": "0x5AEa5775959fBC2557Cc8789bC1bf90A239D9a91",
      "chainId": 324,
      "decimals": 18,
      "logoURI": "https://tokens.pancakeswap.finance/images/zksync/0x5AEa5775959fBC2557Cc8789bC1bf90A239D9a91.png"
    },
    {
      "name": "USD Coin (Native)",
      "symbol": "USDC",
      "address": "0x1d17CBcF0D6D143135aE902365D2E5e2A16538D4",
      "chainId": 324,
      "decimals": 6,
      "logoURI": "https://tokens.pancakeswap.finance/images/zksync/0x1d17CBcF0D6D143135aE902365D2E5e2A16538D4.png"
    },
    {
      "name": "Bridged USDC",
      "symbol": "USDC.e",
      "address": "0x3355df6D4c9C3035724Fd0e3914dE96A5a83aaf4",
      "chainId": 324,
      "decimals": 6,
      "logoURI": "https://tokens.pancakeswap.finance/images/zksync/0x3355df6D4c9C3035724Fd0e3914dE96A5a83aaf4.png"
    },
    {
      "name": "Rocket Pool ETH",
      "symbol": "rETH",
      "address": "0x32Fd44bB869620C0EF993754c8a00Be67C464806",
      "chainId": 324,
      "decimals": 18,
      "logoURI": "https://tokens.pancakeswap.finance/images/zksync/0x32Fd44bB869620C0EF993754c8a00Be67C464806.png"
    },
    {
      "name": "USD Plus",
      "symbol": "USD+",
      "address": "0x8E86e46278518EFc1C5CEd245cBA2C7e3ef11557",
      "chainId": 324,
      "decimals": 6,
      "logoURI": "https://tokens.pancakeswap.finance/images/zksync/0x8E86e46278518EFc1C5CEd245cBA2C7e3ef11557.png"
    },
    {
      "name": "Tether USD",
      "symbol": "USDT",
      "address": "0x493257fD37EDB34451f62EDf8D2a0C418852bA4C",
      "chainId": 324,
      "decimals": 6,
      "logoURI": "https://tokens.pancakeswap.finance/images/zksync/0x493257fD37EDB34451f62EDf8D2a0C418852bA4C.png"
    },
    {
      "name": "Binance USD",
      "symbol": "BUSD",
      "address": "0x2039bb4116B4EFc145Ec4f0e2eA75012D6C0f181",
      "chainId": 324,
      "decimals": 18,
      "logoURI": "https://tokens.pancakeswap.finance/images/zksync/0x2039bb4116B4EFc145Ec4f0e2eA75012D6C0f181.png"
    },
    {
      "name": "Wrapped BTC",
      "symbol": "WBTC",
      "address": "0xBBeB516fb02a01611cBBE0453Fe3c580D7281011",
      "chainId": 324,
      "decimals": 8,
      "logoURI": "https://tokens.pancakeswap.finance/images/zksync/0xBBeB516fb02a01611cBBE0453Fe3c580D7281011.png"
    },
    {
      "name": "TES",
      "symbol": "TES",
      "address": "0xCab3F741Fa54e79E34753B95717b23018332b8AC",
      "chainId": 324,
      "decimals": 18,
      "logoURI": "https://tokens.pancakeswap.finance/images/zksync/0xCab3F741Fa54e79E34753B95717b23018332b8AC.png"
    },
    {
      "name": "Wrapped liquid staked Ether 2.0",
      "symbol": "wstETH",
      "address": "0x703b52F2b28fEbcB60E1372858AF5b18849FE867",
      "chainId": 324,
      "decimals": 18,
      "logoURI": "https://tokens.pancakeswap.finance/images/zksync/0x703b52F2b28fEbcB60E1372858AF5b18849FE867.png"
    },
    {
      "name": "Zeek Coin",
      "symbol": "MEOW",
      "address": "0x79db8c67d0c33203da4Efb58F7D325E1e0d4d692",
      "chainId": 324,
      "decimals": 18,
      "logoURI": "https://tokens.pancakeswap.finance/images/zksync/0x79db8c67d0c33203da4Efb58F7D325E1e0d4d692.png"
    },
    {
      "name": "DAI Stablecoin",
      "symbol": "DAI",
      "address": "0x4B9eb6c0b6ea15176BBF62841C6B2A8a398cb656",
      "chainId": 324,
      "decimals": 18,
      "logoURI": "https://tokens.pancakeswap.finance/images/zksync/0x4B9eb6c0b6ea15176BBF62841C6B2A8a398cb656.png"
    },
    {
      "name": "Wrapped Ether Native Bridge",
      "symbol": "WETH.e",
      "address": "0xf00DAD97284D0c6F06dc4Db3c32454D4292c6813",
      "chainId": 324,
      "decimals": 18,
      "logoURI": "https://tokens.pancakeswap.finance/images/zksync/0xf00DAD97284D0c6F06dc4Db3c32454D4292c6813.png"
    },
    {
      "name": "Gravita Debt Token",
      "symbol": "GRAI",
      "address": "0x5FC44E95eaa48F9eB84Be17bd3aC66B6A82Af709",
      "chainId": 324,
      "decimals": 18,
      "logoURI": "https://tokens.pancakeswap.finance/images/zksync/0x5FC44E95eaa48F9eB84Be17bd3aC66B6A82Af709.png"
    },
    {
      "name": "USDT+",
      "symbol": "USDT+",
      "address": "0xBb8D60008A08b1828E02120F1a952D295036eF3d",
      "chainId": 324,
      "decimals": 6,
      "logoURI": "https://tokens.pancakeswap.finance/images/zksync/0xBb8D60008A08b1828E02120F1a952D295036eF3d.png"
    },
    {
      "name": "Holdstation",
      "symbol": "HOLD",
      "address": "0xed4040fD47629e7c8FBB7DA76bb50B3e7695F0f2",
      "chainId": 324,
      "decimals": 18,
      "logoURI": "https://tokens.pancakeswap.finance/images/zksync/0xed4040fD47629e7c8FBB7DA76bb50B3e7695F0f2.png"
    },
    {
      "name": "zkSync",
      "symbol": "ZK",
      "address": "0x5A7d6b2F92C77FAD6CCaBd7EE0624E64907Eaf3E",
      "chainId": 324,
      "decimals": 18,
      "logoURI": "https://tokens.pancakeswap.finance/images/zksync/0x5A7d6b2F92C77FAD6CCaBd7EE0624E64907Eaf3E.png"
    },
    {
      "name": "ZKE",
      "symbol": "ZKE",
      "address": "0x7b3e1236c39ddD2e61cF6Da6ac6D11193238ccB0",
      "chainId": 324,
      "decimals": 18,
      "logoURI": "https://tokens.pancakeswap.finance/images/zksync/0x7b3e1236c39ddD2e61cF6Da6ac6D11193238ccB0.png"
    },
    {
      "name": "ReactorFusion",
      "symbol": "RF",
      "address": "0x5f7CBcb391d33988DAD74D6Fd683AadDA1123E4D",
      "chainId": 324,
      "decimals": 18,
      "logoURI": "https://tokens.pancakeswap.finance/images/zksync/0x5f7CBcb391d33988DAD74D6Fd683AadDA1123E4D.png"
    }
  ]
}

=== LaozpGZ/SimpleFlow-monorepo/apps/token-list/lists/pancakeswap-base-default.json
{
  "name": "PancakeSwap Base Default",
  "timestamp": "2024-09-12T15:43:00.411Z",
  "version": {
    "major": 0,
    "minor": 0,
    "patch": 17
  },
  "logoURI": "https://pancakeswap.finance/logo.png",
  "keywords": ["pancakeswap", "default", "base"],
  "tokens": [
    {
      "name": "Wrapped Ether",
      "symbol": "WETH",
      "address": "0x4200000000000000000000000000000000000006",
      "chainId": 8453,
      "decimals": 18,
      "logoURI": "https://tokens.pancakeswap.finance/images/symbol/weth.png"
    },
    {
      "name": "Base tBTC v2",
      "symbol": "tbtc",
      "address": "0x236aa50979D5f3De3Bd1Eeb40E81137F22ab794b",
      "chainId": 8453,
      "decimals": 18,
      "logoURI": "https://tokens.pancakeswap.finance/images/base/0x236aa50979D5f3De3Bd1Eeb40E81137F22ab794b.png"
    },
    {
      "name": "USD Base Coin",
      "symbol": "USDbC",
      "address": "0xd9aAEc86B65D86f6A7B5B1b0c42FFA531710b6CA",
      "chainId": 8453,
      "decimals": 6,
      "logoURI": "https://tokens.pancakeswap.finance/images/base/0xd9aAEc86B65D86f6A7B5B1b0c42FFA531710b6CA.png"
    },
    {
      "name": "USD Coin",
      "symbol": "USDC",
      "address": "0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913",
      "chainId": 8453,
      "decimals": 6,
      "logoURI": "https://tokens.pancakeswap.finance/images/symbol/usdc.png"
    },
    {
      "name": "Dai Stablecoin",
      "symbol": "DAI",
      "address": "0x50c5725949A6F0c72E6C4a641F24049A917DB0Cb",
      "chainId": 8453,
      "decimals": 18,
      "logoURI": "https://tokens.pancakeswap.finance/images/symbol/dai.png"
    },
    {
      "name": "Coinbase Wrapped Staked ETH",
      "symbol": "cbETH",
      "address": "0x2Ae3F1Ec7F1F5012CFEab0185bfc7aa3cf0DEc22",
      "chainId": 8453,
      "decimals": 18,
      "logoURI": "https://tokens.pancakeswap.finance/images/base/0x2Ae3F1Ec7F1F5012CFEab0185bfc7aa3cf0DEc22.png"
    },
    {
      "name": "Axelar Wrapped USDC",
      "symbol": "axlUSDC",
      "address": "0xEB466342C4d449BC9f53A865D5Cb90586f405215",
      "chainId": 8453,
      "decimals": 6,
      "logoURI": "https://tokens.pancakeswap.finance/images/base/0xEB466342C4d449BC9f53A865D5Cb90586f405215.png"
    },
    {
      "name": "SABLE",
      "symbol": "SABLE",
      "address": "0xE5393cdBC4Fe7B62F1d76A990Ca7Da17ad718313",
      "chainId": 8453,
      "decimals": 18,
      "logoURI": "https://tokens.pancakeswap.finance/images/base/0xE5393cdBC4Fe7B62F1d76A990Ca7Da17ad718313.png"
    },
    {
      "name": "PancakeSwap Token",
      "symbol": "CAKE",
      "address": "0x3055913c90Fcc1A6CE9a358911721eEb942013A1",
      "chainId": 8453,
      "decimals": 18,
      "logoURI": "https://tokens.pancakeswap.finance/images/base/0x3055913c90Fcc1A6CE9a358911721eEb942013A1.png"
    },
    {
      "name": "Wrapped liquid staked Ether 2.0",
      "symbol": "wstETH",
      "address": "0xc1CBa3fCea344f92D9239c08C0568f6F2F0ee452",
      "chainId": 8453,
      "decimals": 18,
      "logoURI": "https://tokens.pancakeswap.finance/images/base/0xc1CBa3fCea344f92D9239c08C0568f6F2F0ee452.png"
    },
    {
      "name": "USD+",
      "symbol": "USD+",
      "address": "0xB79DD08EA68A908A97220C76d19A6aA9cBDE4376",
      "chainId": 8453,
      "decimals": 6,
      "logoURI": "https://tokens.pancakeswap.finance/images/base/0xB79DD08EA68A908A97220C76d19A6aA9cBDE4376.png"
    },
    {
      "name": "Brett",
      "symbol": "BRETT",
      "address": "0x532f27101965dd16442E59d40670FaF5eBB142E4",
      "chainId": 8453,
      "decimals": 18,
      "logoURI": "https://tokens.pancakeswap.finance/images/base/0x532f27101965dd16442E59d40670FaF5eBB142E4.png"
    },
    {
      "name": "Degen",
      "symbol": "DEGEN",
      "address": "0x4ed4E862860beD51a9570b96d89aF5E1B0Efefed",
      "chainId": 8453,
      "decimals": 18,
      "logoURI": "https://tokens.pancakeswap.finance/images/base/0x4ed4E862860beD51a9570b96d89aF5E1B0Efefed.png"
    },
    {
      "name": "Aerodrome",
      "symbol": "AERO",
      "address": "0x940181a94A35A4569E4529A3CDfB74e38FD98631",
      "chainId": 8453,
      "decimals": 18,
      "logoURI": "https://tokens.pancakeswap.finance/images/base/0x940181a94A35A4569E4529A3CDfB74e38FD98631.png"
    },
    {
      "name": "OVN",
      "symbol": "OVN",
      "address": "0xA3d1a8DEB97B111454B294E2324EfAD13a9d8396",
      "chainId": 8453,
      "decimals": 18,
      "logoURI": "https://tokens.pancakeswap.finance/images/base/0xA3d1a8DEB97B111454B294E2324EfAD13a9d8396.png"
    },
    {
      "name": "LayerZero",
      "symbol": "ZRO",
      "address": "0x6985884C4392D348587B19cb9eAAf157F13271cd",
      "chainId": 8453,
      "decimals": 18,
      "logoURI": "https://tokens.pancakeswap.finance/images/base/0x6985884C4392D348587B19cb9eAAf157F13271cd.png"
    },
    {
      "name": "Tether USDT",
      "symbol": "USDT",
      "address": "0xfde4C96c8593536E31F229EA8f37b2ADa2699bb2",
      "chainId": 8453,
      "decimals": 6,
      "logoURI": "https://tokens.pancakeswap.finance/images/symbol/usdt.png"
    },
    {
      "name": "Wrapped eETH",
      "symbol": "weETH",
      "address": "0x04C0599Ae5A44757c0af6F9eC3b93da8976c150A",
      "chainId": 8453,
      "decimals": 18,
      "logoURI": "https://tokens.pancakeswap.finance/images/base/0x04C0599Ae5A44757c0af6F9eC3b93da8976c150A.png"
    },
    {
      "name": "Master Miggles",
      "symbol": "MIGGLES",
      "address": "0xB1a03EdA10342529bBF8EB700a06C60441fEf25d",
      "chainId": 8453,
      "decimals": 18,
      "logoURI": "https://tokens.pancakeswap.finance/images/base/0xB1a03EdA10342529bBF8EB700a06C60441fEf25d.png"
    },
    {
      "name": "USDz",
      "symbol": "USDz",
      "address": "0x04D5ddf5f3a8939889F11E97f8c4BB48317F1938",
      "chainId": 8453,
      "decimals": 18,
      "logoURI": "https://tokens.pancakeswap.finance/images/base/0x04D5ddf5f3a8939889F11E97f8c4BB48317F1938.png"
    },
    {
      "name": "dogwifhat",
      "symbol": "WIF",
      "address": "0x1fba65dE0a9cBD2D1DF82d141897042d36Bb6c86",
      "chainId": 8453,
      "decimals": 18,
      "logoURI": "https://tokens.pancakeswap.finance/images/base/0x1fba65dE0a9cBD2D1DF82d141897042d36Bb6c86.png"
    },
    {
      "name": "Wormhole Wrapped USDT",
      "symbol": "wxUSDT",
      "address": "0xFf0C62A4979400841eFaA6faADb07Ac7d5C98b27",
      "chainId": 8453,
      "decimals": 6,
      "logoURI": "https://tokens.pancakeswap.finance/images/base/0xFf0C62A4979400841eFaA6faADb07Ac7d5C98b27.png"
    },
    {
      "name": "Dola USD Stablecoin",
      "symbol": "DOLA",
      "address": "0x4621b7A9c75199271F773Ebd9A499dbd165c3191",
      "chainId": 8453,
      "decimals": 18,
      "logoURI": "https://tokens.pancakeswap.finance/images/base/0x4621b7A9c75199271F773Ebd9A499dbd165c3191.png"
    },
    {
      "name": "Renzo Restaked ETH",
      "symbol": "ezETH",
      "address": "0x2416092f143378750bb29b79eD961ab195CcEea5",
      "chainId": 8453,
      "decimals": 18,
      "logoURI": "https://tokens.pancakeswap.finance/images/base/0x2416092f143378750bb29b79eD961ab195CcEea5.png"
    },
    {
      "name": "Mog Coin",
      "symbol": "MOG",
      "address": "0x2Da56AcB9Ea78330f947bD57C54119Debda7AF71",
      "chainId": 8453,
      "decimals": 18,
      "logoURI": "https://tokens.pancakeswap.finance/images/base/0x2Da56AcB9Ea78330f947bD57C54119Debda7AF71.png"
    },
    {
      "name": "Electronic Dollar",
      "symbol": "eUSD",
      "address": "0xCfA3Ef56d303AE4fAabA0592388F19d7C3399FB4",
      "chainId": 8453,
      "decimals": 18,
      "logoURI": "https://tokens.pancakeswap.finance/images/base/0xCfA3Ef56d303AE4fAabA0592388F19d7C3399FB4.png"
    },
    {
      "name": "Coinbase Wrapped BTC",
      "symbol": "cbBTC",
      "address": "0xcbB7C0000aB88B473b1f5aFd9ef808440eed33Bf",
      "chainId": 8453,
      "decimals": 8,
      "logoURI": "https://tokens.pancakeswap.finance/images/base/0xcbB7C0000aB88B473b1f5aFd9ef808440eed33Bf.png"
    }
  ]
}
