=== LaozpGZ/SimpleFlow-monorepo/apps/token-list/test/schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "pancakeswap",
  "title": "PancakeSwap Token List",
  "description": "Schema for lists of tokens compatible with the PancakeSwap Interface, including Uniswap standard and PancakeSwap Aptos",
  "definitions": {
    "Version": {
      "type": "object",
      "description": "The version of the list, used in change detection",
      "examples": [
        {
          "major": 1,
          "minor": 0,
          "patch": 0
        }
      ],
      "additionalProperties": false,
      "properties": {
        "major": {
          "type": "integer",
          "description": "The major version of the list. Must be incremented when tokens are removed from the list or token addresses are changed.",
          "minimum": 0,
          "examples": [1, 2]
        },
        "minor": {
          "type": "integer",
          "description": "The minor version of the list. Must be incremented when tokens are added to the list.",
          "minimum": 0,
          "examples": [0, 1]
        },
        "patch": {
          "type": "integer",
          "description": "The patch version of the list. Must be incremented for any changes to the list.",
          "minimum": 0,
          "examples": [0, 1]
        }
      },
      "required": ["major", "minor", "patch"]
    },
    "TagIdentifier": {
      "type": "string",
      "description": "The unique identifier of a tag",
      "minLength": 1,
      "maxLength": 10,
      "pattern": "^[\\w]+$",
      "examples": ["compound", "stablecoin"]
    },
    "ExtensionIdentifier": {
      "type": "string",
      "description": "The name of a token extension property",
      "minLength": 1,
      "maxLength": 40,
      "pattern": "^[\\w]+$",
      "examples": ["color", "is_fee_on_transfer", "aliases"]
    },
    "ExtensionMap": {
      "type": "object",
      "description": "An object containing any arbitrary or vendor-specific token metadata",
      "maxProperties": 10,
      "propertyNames": {
        "$ref": "#/definitions/ExtensionIdentifier"
      },
      "additionalProperties": {
        "$ref": "#/definitions/ExtensionValue"
      },
      "examples": [
        {
          "color": "#000000",
          "is_verified_by_me": true
        },
        {
          "x-bridged-addresses-by-chain": {
            "1": {
              "bridgeAddress": "0x4200000000000000000000000000000000000010",
              "tokenAddress": "0x4200000000000000000000000000000000000010"
            }
          }
        }
      ]
    },
    "ExtensionPrimitiveValue": {
      "anyOf": [
        {
          "type": "string",
          "minLength": 1,
          "maxLength": 42,
          "examples": ["#00000"]
        },
        {
          "type": "boolean",
          "examples": [true]
        },
        {
          "type": "number",
          "examples": [15]
        },
        {
          "type": "null"
        }
      ]
    },
    "ExtensionValue": {
      "anyOf": [
        {
          "$ref": "#/definitions/ExtensionPrimitiveValue"
        },
        {
          "type": "object",
          "maxProperties": 10,
          "propertyNames": {
            "$ref": "#/definitions/ExtensionIdentifier"
          },
          "additionalProperties": {
            "$ref": "#/definitions/ExtensionValueInner0"
          }
        }
      ]
    },
    "ExtensionValueInner0": {
      "anyOf": [
        {
          "$ref": "#/definitions/ExtensionPrimitiveValue"
        },
        {
          "type": "object",
          "maxProperties": 10,
          "propertyNames": {
            "$ref": "#/definitions/ExtensionIdentifier"
          },
          "additionalProperties": {
            "$ref": "#/definitions/ExtensionValueInner1"
          }
        }
      ]
    },
    "ExtensionValueInner1": {
      "anyOf": [
        {
          "$ref": "#/definitions/ExtensionPrimitiveValue"
        }
      ]
    },
    "TagDefinition": {
      "type": "object",
      "description": "Definition of a tag that can be associated with a token via its identifier",
      "additionalProperties": false,
      "properties": {
        "name": {
          "type": "string",
          "description": "The name of the tag",
          "pattern": "^[ \\w]+$",
          "minLength": 1,
          "maxLength": 20
        },
        "description": {
          "type": "string",
          "description": "A user-friendly description of the tag",
          "pattern": "^[ \\w\\.,:]+$",
          "minLength": 1,
          "maxLength": 200
        }
      },
      "required": ["name", "description"],
      "examples": [
        {
          "name": "Stablecoin",
          "description": "A token with value pegged to another asset"
        }
      ]
    },
    "TokenInfo": {
      "type": "object",
      "description": "Metadata for a single token in a token list",
      "additionalProperties": false,
      "properties": {
        "chainId": {
          "type": "integer",
          "description": "The chain ID of the Ethereum network where this token is deployed",
          "minimum": 1,
          "examples": [1, 42]
        },
        "address": {
          "type": "string",
          "description": "The checksummed address of the token on the specified chain ID",
          "pattern": "^0x[a-fA-F0-9]{40}$",
          "examples": ["0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48"]
        },
        "decimals": {
          "type": "integer",
          "description": "The number of decimals for the token balance",
          "minimum": 0,
          "maximum": 255,
          "examples": [18]
        },
        "name": {
          "type": "string",
          "description": "The name of the token",
          "minLength": 1,
          "maxLength": 40,
          "pattern": "^[ \\w.'+\\-%/À-ÖØ-öø-ÿ:&\\[\\]\\(\\)]+$",
          "examples": ["USD Coin"]
        },
        "symbol": {
          "type": "string",
          "description": "The symbol for the token; must be alphanumeric",
          "pattern": "^[a-zA-Z0-9+\\-%/$.\\s]+$",
          "minLength": 1,
          "maxLength": 20,
          "examples": ["USDC"]
        },
        "logoURI": {
          "type": "string",
          "description": "A URI to the token logo asset; if not set, interface will attempt to find a logo based on the token address; suggest SVG or PNG of size 64x64",
          "format": "uri",
          "examples": ["ipfs://QmXfzKRvjZz3u5JRgC4v5mGVbm9ahrUiB4DgzHBsnWbTMM"]
        },
        "tags": {
          "type": "array",
          "description": "An array of tag identifiers associated with the token; tags are defined at the list level",
          "items": {
            "$ref": "#/definitions/TagIdentifier"
          },
          "maxItems": 10,
          "examples": ["stablecoin", "compound"]
        },
        "extensions": {
          "$ref": "#/definitions/ExtensionMap"
        }
      },
      "required": ["chainId", "address", "decimals", "name", "symbol"]
    },
    "AptosTokenInfo": {
      "type": "object",
      "description": "Metadata for a single token in a token list",
      "additionalProperties": false,
      "properties": {
        "chainId": {
          "type": "integer",
          "description": "The chain ID of the Aptos network where this token is deployed, 0 is devent",
          "minimum": 0,
          "examples": [1, 42]
        },
        "address": {
          "type": "string",
          "description": "The address of the coin on the specified chain ID",
          "examples": ["0x1::aptos_coin::AptosCoin"]
        },
        "decimals": {
          "type": "integer",
          "description": "The number of decimals for the token balance",
          "minimum": 0,
          "maximum": 255,
          "examples": [18]
        },
        "name": {
          "type": "string",
          "description": "The name of the token",
          "minLength": 1,
          "maxLength": 40,
          "pattern": "^[ \\w.'+\\-%/À-ÖØ-öø-ÿ:&\\[\\]\\(\\)]+$",
          "examples": ["USD Coin"]
        },
        "symbol": {
          "type": "string",
          "description": "The symbol for the token; must be alphanumeric",
          "pattern": "^[a-zA-Z0-9+\\-%/$.]+$",
          "minLength": 1,
          "maxLength": 20,
          "examples": ["USDC"]
        },
        "logoURI": {
          "type": "string",
          "description": "A URI to the token logo asset; if not set, interface will attempt to find a logo based on the token address; suggest SVG or PNG of size 64x64",
          "format": "uri",
          "examples": ["ipfs://QmXfzKRvjZz3u5JRgC4v5mGVbm9ahrUiB4DgzHBsnWbTMM"]
        },
        "tags": {
          "type": "array",
          "description": "An array of tag identifiers associated with the token; tags are defined at the list level",
          "items": {
            "$ref": "#/definitions/TagIdentifier"
          },
          "maxItems": 10,
          "examples": ["stablecoin", "compound"]
        },
        "extensions": {
          "$ref": "#/definitions/ExtensionMap"
        }
      },
      "required": ["chainId", "address", "decimals", "name", "symbol"]
    },
    "SolanaTokenInfo": {
      "type": "object",
      "description": "Metadata for a single token in a token list",
      "additionalProperties": false,
      "properties": {
        "chainId": {
          "type": "integer",
          "description": "The chain ID of the Solana network where this token is deployed",
          "minimum": 0,
          "examples": [101]
        },
        "address": {
          "type": "string",
          "description": "The address of the coin on the specified chain ID",
          "pattern": "^[1-9A-HJ-NP-Za-km-z]{32,44}$",
          "examples": ["So11111111111111111111111111111111111111112"]
        },
        "programId": {
          "type": "string",
          "description": "The program ID of the token on the specified chain ID",
          "pattern": "^[1-9A-HJ-NP-Za-km-z]{32,44}$",
          "examples": ["TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"]
        },
        "decimals": {
          "type": "integer",
          "description": "The number of decimals for the token balance",
          "minimum": 0,
          "maximum": 255,
          "examples": [18]
        },
        "name": {
          "type": "string",
          "description": "The name of the token",
          "minLength": 1,
          "maxLength": 40,
          "pattern": "^[ \\w'+\\-%/À-ÖØ-öø-ÿ:&\\[\\]\\(\\)\\$]+$",
          "examples": ["USD Coin"]
        },
        "symbol": {
          "type": "string",
          "description": "The symbol for the token; must be alphanumeric",
          "pattern": "^[a-zA-Z0-9+\\-%/$_]+$",
          "minLength": 1,
          "maxLength": 20,
          "examples": ["USDC"]
        },
        "logoURI": {
          "type": "string",
          "description": "A URI to the token logo asset; if not set, interface will attempt to find a logo based on the token address; suggest SVG or PNG of size 64x64",
          "format": "uri",
          "examples": ["ipfs://QmXfzKRvjZz3u5JRgC4v5mGVbm9ahrUiB4DgzHBsnWbTMM"]
        },
        "tags": {
          "type": "array",
          "description": "An array of tag identifiers associated with the token; tags are defined at the list level",
          "items": {
            "$ref": "#/definitions/TagIdentifier"
          },
          "maxItems": 10,
          "examples": ["stablecoin", "compound"]
        },
        "extensions": {
          "$ref": "#/definitions/ExtensionMap"
        }
      },
      "required": ["chainId", "address", "programId", "decimals", "name", "symbol"]
    }
  },
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "name": {
      "type": "string",
      "description": "The name of the token list",
      "minLength": 1,
      "maxLength": 30,
      "pattern": "^[\\w ]+$",
      "examples": ["My Token List"]
    },
    "timestamp": {
      "type": "string",
      "format": "date-time",
      "description": "The timestamp of this list version; i.e. when this immutable version of the list was created"
    },
    "schema": {
      "type": "string"
    },
    "version": {
      "$ref": "#/definitions/Version"
    },
    "tokens": {
      "type": "array",
      "description": "The list of tokens included in the list",
      "minItems": 1,
      "maxItems": 10000
    },
    "keywords": {
      "type": "array",
      "description": "Keywords associated with the contents of the list; may be used in list discoverability",
      "items": {
        "type": "string",
        "description": "A keyword to describe the contents of the list",
        "minLength": 1,
        "maxLength": 20,
        "pattern": "^[\\w ]+$",
        "examples": ["compound", "lending", "personal tokens"]
      },
      "maxItems": 20,
      "uniqueItems": true
    },
    "tags": {
      "type": "object",
      "description": "A mapping of tag identifiers to their name and description",
      "propertyNames": {
        "$ref": "#/definitions/TagIdentifier"
      },
      "additionalProperties": {
        "$ref": "#/definitions/TagDefinition"
      },
      "maxProperties": 20,
      "examples": [
        {
          "stablecoin": {
            "name": "Stablecoin",
            "description": "A token with value pegged to another asset"
          }
        }
      ]
    },
    "logoURI": {
      "type": "string",
      "description": "A URI for the logo of the token list; prefer SVG or PNG of size 256x256",
      "format": "uri",
      "examples": ["ipfs://QmXfzKRvjZz3u5JRgC4v5mGVbm9ahrUiB4DgzHBsnWbTMM"]
    }
  },
  "allOf": [
    {
      "if": {
        "properties": {
          "schema": {
            "const": "aptos"
          }
        },
        "required": ["name", "timestamp", "version", "tokens", "schema"]
      },
      "then": {
        "properties": {
          "tokens": {
            "items": {
              "$ref": "#/definitions/AptosTokenInfo"
            },
            "type": "array",
            "description": "The list of tokens included in the list",
            "minItems": 1,
            "maxItems": 10000
          }
        }
      }
    },
    {
      "if": {
        "properties": {
          "schema": {
            "const": "solana"
          }
        },
        "required": ["name", "timestamp", "version", "tokens", "schema"]
      },
      "then": {
        "properties": {
          "tokens": {
            "items": {
              "$ref": "#/definitions/SolanaTokenInfo"
            },
            "type": "array",
            "description": "The list of tokens included in the list",
            "minItems": 1,
            "maxItems": 10000
          }
        }
      }
    },
    {
      "else": {
        "properties": {
          "tokens": {
            "items": {
              "$ref": "#/definitions/TokenInfo"
            },
            "type": "array",
            "description": "The list of tokens included in the list",
            "minItems": 1,
            "maxItems": 10000
          }
        }
      }
    }
  ],
  "required": ["name", "timestamp", "version", "tokens"]
}

=== LaozpGZ/SimpleFlow-monorepo/apps/token-list/lists/pancakeswap-scroll-default.json
{
  "name": "PancakeSwap Scroll Default",
  "timestamp": "2023-10-18T06:20:04.942Z",
  "version": {
    "major": 0,
    "minor": 0,
    "patch": 4
  },
  "logoURI": "https://pancakeswap.finance/logo.png",
  "keywords": ["pancakeswap", "default", "scroll"],
  "tokens": [
    {
      "name": "Wrapped Ether",
      "symbol": "WETH",
      "address": "0x5300000000000000000000000000000000000004",
      "chainId": 534352,
      "decimals": 18,
      "logoURI": "https://tokens.pancakeswap.finance/images/symbol/weth.png"
    },
    {
      "name": "Wrapped BTC",
      "symbol": "WBTC",
      "address": "0x3C1BCa5a656e69edCD0D4E36BEbb3FcDAcA60Cf1",
      "chainId": 534352,
      "decimals": 8,
      "logoURI": "https://tokens.pancakeswap.finance/images/symbol/wbtc.png"
    },
    {
      "name": "Tether USD",
      "symbol": "USDT",
      "address": "0xf55BEC9cafDbE8730f096Aa55dad6D22d44099Df",
      "chainId": 534352,
      "decimals": 6,
      "logoURI": "https://tokens.pancakeswap.finance/images/symbol/usdt.png"
    },
    {
      "name": "USD Coin",
      "symbol": "USDC",
      "address": "0x06eFdBFf2a14a7c8E15944D1F4A48F9F95F663A4",
      "chainId": 534352,
      "decimals": 6,
      "logoURI": "https://tokens.pancakeswap.finance/images/symbol/usdc.png"
    }
  ]
}

=== LaozpGZ/SimpleFlow-monorepo/apps/token-list/lists/pancakeswap-aptos.json
{
  "name": "PancakeSwap Aptos",
  "timestamp": "2025-01-15T01:44:00.049Z",
  "version": {
    "major": 0,
    "minor": 0,
    "patch": 27
  },
  "logoURI": "https://pancakeswap.finance/logo.png",
  "keywords": ["pancakeswap", "aptos"],
  "schema": "aptos",
  "tokens": [
    {
      "name": "PancakeSwap Token",
      "symbol": "CAKE",
      "chainId": 1,
      "decimals": 8,
      "address": "0x159df6b7689437016108a019fd5bef736bac692b6d4a1f10c941f6fbb9a74ca6::oft::CakeOFT",
      "logoURI": "https://tokens.pancakeswap.finance/images/aptos/0x159df6b7689437016108a019fd5bef736bac692b6d4a1f10c941f6fbb9a74ca6::oft::CakeOFT.png"
    },
    {
      "name": "Aptos Bitcoin",
      "symbol": "aBTC",
      "chainId": 1,
      "decimals": 8,
      "address": "0x4e1854f6d332c9525e258fb6e66f84b6af8aba687bbcb832a24768c4e175feec::abtc::ABTC",
      "logoURI": "https://tokens.pancakeswap.finance/images/0x4e1854f6d332c9525e258fb6e66f84b6af8aba687bbcb832a24768c4e175feec::abtc::ABTC.png"
    },
    {
      "name": "Amnis Finance",
      "symbol": "amAPT",
      "chainId": 1,
      "decimals": 8,
      "address": "0x111ae3e5bc816a5e63c2da97d0aa3886519e0cd5e4b046659fa35796bd11542a::amapt_token::AmnisApt",
      "logoURI": "https://tokens.pancakeswap.finance/images/aptos/0x111ae3e5bc816a5e63c2da97d0aa3886519e0cd5e4b046659fa35796bd11542a::amapt_token::AmnisApt.png"
    },
    {
      "name": "Aptos Coin",
      "symbol": "APT",
      "chainId": 1,
      "decimals": 8,
      "address": "0x1::aptos_coin::AptosCoin",
      "logoURI": "https://tokens.pancakeswap.finance/images/symbol/apt.png"
    },
    {
      "name": "Blocto Token",
      "symbol": "BLT",
      "chainId": 1,
      "decimals": 8,
      "address": "0xfbab9fb68bd2103925317b6a540baa20087b1e7a7a4eb90badee04abb6b5a16f::blt::Blt",
      "logoURI": "https://tokens.pancakeswap.finance/images/aptos/0xfbab9fb68bd2103925317b6a540baa20087b1e7a7a4eb90badee04abb6b5a16f::blt::Blt.png"
    },
    {
      "name": "Celer - Binance Coin",
      "symbol": "ceBNB",
      "chainId": 1,
      "decimals": 8,
      "address": "0x8d87a65ba30e09357fa2edea2c80dbac296e5dec2b18287113500b902942929d::celer_coin_manager::BnbCoin",
      "logoURI": "https://tokens.pancakeswap.finance/images/symbol/bnb.png"
    },
    {
      "name": "Celer - Binance USD",
      "symbol": "ceBUSD",
      "chainId": 1,
      "decimals": 8,
      "address": "0x8d87a65ba30e09357fa2edea2c80dbac296e5dec2b18287113500b902942929d::celer_coin_manager::BusdCoin",
      "logoURI": "https://tokens.pancakeswap.finance/images/symbol/busd.png"
    },
    {
      "name": "Celer - Dai Stablecoin",
      "symbol": "ceDAI",
      "chainId": 1,
      "decimals": 8,
      "address": "0x8d87a65ba30e09357fa2edea2c80dbac296e5dec2b18287113500b902942929d::celer_coin_manager::DaiCoin",
      "logoURI": "https://tokens.pancakeswap.finance/images/symbol/dai.png"
    },
    {
      "name": "Celer - USD Coin",
      "symbol": "ceUSDC",
      "chainId": 1,
      "decimals": 6,
      "address": "0x8d87a65ba30e09357fa2edea2c80dbac296e5dec2b18287113500b902942929d::celer_coin_manager::UsdcCoin",
      "logoURI": "https://tokens.pancakeswap.finance/images/symbol/usdc.png"
    },
    {
      "name": "Celer - Tether USD",
      "symbol": "ceUSDT",
      "chainId": 1,
      "decimals": 6,
      "address": "0x8d87a65ba30e09357fa2edea2c80dbac296e5dec2b18287113500b902942929d::celer_coin_manager::UsdtCoin",
      "logoURI": "https://tokens.pancakeswap.finance/images/symbol/usdt.png"
    },
    {
      "name": "Celer - Wrapped BTC",
      "symbol": "ceWBTC",
      "chainId": 1,
      "decimals": 8,
      "address": "0x8d87a65ba30e09357fa2edea2c80dbac296e5dec2b18287113500b902942929d::celer_coin_manager::WbtcCoin",
      "logoURI": "https://tokens.pancakeswap.finance/images/symbol/wbtc.png"
    },
    {
      "name": "Celer - Wrapped Ether",
      "symbol": "ceWETH",
      "chainId": 1,
      "decimals": 8,
      "address": "0x8d87a65ba30e09357fa2edea2c80dbac296e5dec2b18287113500b902942929d::celer_coin_manager::WethCoin",
      "logoURI": "https://tokens.pancakeswap.finance/images/symbol/weth.png"
    },
    {
      "name": "GUI INU",
      "symbol": "GUI",
      "chainId": 1,
      "decimals": 6,
      "address": "0xe4ccb6d39136469f376242c31b34d10515c8eaaa38092f804db8e08a8f53c5b2::assets_v1::EchoCoin002",
      "logoURI": "https://tokens.pancakeswap.finance/images/aptos/0xe4ccb6d39136469f376242c31b34d10515c8eaaa38092f804db8e08a8f53c5b2::assets_v1::EchoCoin002"
    },
    {
      "name": "LayerZero - USD Coin",
      "symbol": "lzUSDC",
      "chainId": 1,
      "decimals": 6,
      "address": "0xf22bede237a07e121b56d91a491eb7bcdfd1f5907926a9e58338f964a01b17fa::asset::USDC",
      "logoURI": "https://tokens.pancakeswap.finance/images/symbol/usdc.png"
    },
    {
      "name": "LayerZero - Tether USD",
      "symbol": "lzUSDT",
      "chainId": 1,
      "decimals": 6,
      "address": "0xf22bede237a07e121b56d91a491eb7bcdfd1f5907926a9e58338f964a01b17fa::asset::USDT",
      "logoURI": "https://tokens.pancakeswap.finance/images/symbol/usdt.png"
    },
    {
      "name": "LayerZero - Wrapped Ether",
      "symbol": "lzWETH",
      "chainId": 1,
      "decimals": 6,
      "address": "0xf22bede237a07e121b56d91a491eb7bcdfd1f5907926a9e58338f964a01b17fa::asset::WETH",
      "logoURI": "https://tokens.pancakeswap.finance/images/symbol/weth.png"
    },
    {
      "name": "Meeiro",
      "symbol": "MEE",
      "chainId": 1,
      "decimals": 6,
      "address": "0xe9c192ff55cffab3963c695cff6dbf9dad6aff2bb5ac19a6415cad26a81860d9::mee_coin::MeeCoin",
      "logoURI": "https://tokens.pancakeswap.finance/images/aptos/0xe9c192ff55cffab3963c695cff6dbf9dad6aff2bb5ac19a6415cad26a81860d9::mee_coin::MeeCoin.png"
    },
    {
      "name": "MOD Token",
      "symbol": "MOD",
      "chainId": 1,
      "decimals": 8,
      "address": "0x6f986d146e4a90b828d8c12c14b6f4e003fdff11a8eecceceb63744363eaac01::mod_coin::MOD",
      "logoURI": "https://tokens.pancakeswap.finance/images/aptos/0x6f986d146e4a90b828d8c12c14b6f4e003fdff11a8eecceceb63744363eaac01::mod_coin::MOD.png"
    },
    {
      "name": "Mojito",
      "symbol": "MOJO",
      "chainId": 1,
      "decimals": 8,
      "address": "0x881ac202b1f1e6ad4efcff7a1d0579411533f2502417a19211cfc49751ddb5f4::coin::MOJO",
      "logoURI": "https://tokens.pancakeswap.finance/images/aptos/0x881ac202b1f1e6ad4efcff7a1d0579411533f2502417a19211cfc49751ddb5f4::coin::MOJO.png"
    },
    {
      "name": "MOOMOO Token",
      "symbol": "MOOMOO",
      "chainId": 1,
      "decimals": 8,
      "address": "0xc5fbbcc4637aeebb4e732767abee8a21f2b0776f73b73e16ce13e7d31d6700da::MOOMOO::MOOMOO",
      "logoURI": "https://tokens.pancakeswap.finance/images/aptos/0xc5fbbcc4637aeebb4e732767abee8a21f2b0776f73b73e16ce13e7d31d6700da::MOOMOO::MOOMOO.png"
    },
    {
      "name": "BlueMove",
      "symbol": "MOVE",
      "chainId": 1,
      "decimals": 8,
      "address": "0x27fafcc4e39daac97556af8a803dbb52bcb03f0821898dc845ac54225b9793eb::move_coin::MoveCoin",
      "logoURI": "https://tokens.pancakeswap.finance/images/aptos/0x27fafcc4e39daac97556af8a803dbb52bcb03f0821898dc845ac54225b9793eb::move_coin::MoveCoin.png"
    },
    {
      "name": "Ditto Staked Aptos",
      "symbol": "stAPT",
      "chainId": 1,
      "decimals": 8,
      "address": "0xd11107bdf0d6d7040c6c0bfbdecb6545191fdf13e8d8d259952f53e1713f61b5::staked_coin::StakedAptos",
      "logoURI": "https://tokens.pancakeswap.finance/images/aptos/0xd11107bdf0d6d7040c6c0bfbdecb6545191fdf13e8d8d259952f53e1713f61b5::staked_coin::StakedAptos.png"
    },
    {
      "name": "Amnis Staked Aptos",
      "symbol": "stAPT",
      "chainId": 1,
      "decimals": 8,
      "address": "0x111ae3e5bc816a5e63c2da97d0aa3886519e0cd5e4b046659fa35796bd11542a::stapt_token::StakedApt",
      "logoURI": "https://tokens.pancakeswap.finance/images/aptos/0x111ae3e5bc816a5e63c2da97d0aa3886519e0cd5e4b046659fa35796bd11542a::stapt_token::StakedApt"
    },
    {
      "name": "Tortuga Staked APT",
      "symbol": "tAPT",
      "chainId": 1,
      "decimals": 8,
      "address": "0x84d7aeef42d38a5ffc3ccef853e1b82e4958659d16a7de736a29c55fbbeb0114::staked_aptos_coin::StakedAptosCoin",
      "logoURI": "https://tokens.pancakeswap.finance/images/aptos/0x84d7aeef42d38a5ffc3ccef853e1b82e4958659d16a7de736a29c55fbbeb0114::staked_aptos_coin::StakedAptosCoin.png"
    },
    {
      "name": "Thala Token",
      "symbol": "THL",
      "chainId": 1,
      "decimals": 8,
      "address": "0x7fd500c11216f0fe3095d0c4b8aa4d64a4e2e04f83758462f2b127255643615::thl_coin::THL",
      "logoURI": "https://tokens.pancakeswap.finance/images/aptos/0x7fd500c11216f0fe3095d0c4b8aa4d64a4e2e04f83758462f2b127255643615::thl_coin::THL.png"
    },
    {
      "name": "Wormhole - Binance USD",
      "symbol": "whBUSD",
      "chainId": 1,
      "decimals": 8,
      "address": "0xccc9620d38c4f3991fa68a03ad98ef3735f18d04717cb75d7a1300dd8a7eed75::coin::T",
      "logoURI": "https://tokens.pancakeswap.finance/images/symbol/busd.png"
    },
    {
      "name": "Wormhole - USD Coin",
      "symbol": "whUSDC",
      "chainId": 1,
      "decimals": 6,
      "address": "0x5e156f1207d0ebfa19a9eeff00d62a282278fb8719f4fab3a586a0a2c0fffbea::coin::T",
      "logoURI": "https://tokens.pancakeswap.finance/images/symbol/usdc.png"
    },
    {
      "name": "Wormhole - Tether USD",
      "symbol": "whUSDT",
      "chainId": 1,
      "decimals": 6,
      "address": "0xa2eda21a58856fda86451436513b867c97eecb4ba099da5775520e0f7492e852::coin::T",
      "logoURI": "https://tokens.pancakeswap.finance/images/symbol/usdt.png"
    },
    {
      "name": "Wormhole - Wrapped Ether",
      "symbol": "whWETH",
      "chainId": 1,
      "decimals": 8,
      "address": "0xcc8a89c8dce9693d354449f1f73e60e14e347417854f029db5bc8e7454008abb::coin::T",
      "logoURI": "https://tokens.pancakeswap.finance/images/symbol/weth.png"
    }
  ]
}

=== LaozpGZ/SimpleFlow-monorepo/apps/token-list/lists/pancakeswap-bnb-mm.json
{
  "name": "PancakeSwap BNB Chain MM",
  "timestamp": "2023-06-29T21:24:06.707Z",
  "version": {
    "major": 0,
    "minor": 0,
    "patch": 4
  },
  "logoURI": "https://pancakeswap.finance/logo.png",
  "keywords": ["pancakeswap", "mm", "bnb"],
  "tokens": [
    {
      "name": "WBNB Token",
      "symbol": "WBNB",
      "address": "0xbb4CdB9CBd36B01bD1cBaEBF2De08d9173bc095c",
      "chainId": 56,
      "decimals": 18,
      "logoURI": "https://tokens.pancakeswap.finance/images/0xbb4CdB9CBd36B01bD1cBaEBF2De08d9173bc095c.png"
    },
    {
      "name": "Binance Pegged ETH",
      "symbol": "ETH",
      "address": "0x2170Ed0880ac9A755fd29B2688956BD959F933F8",
      "chainId": 56,
      "decimals": 18,
      "logoURI": "https://tokens.pancakeswap.finance/images/0x2170Ed0880ac9A755fd29B2688956BD959F933F8.png"
    },
    {
      "name": "Binance Pegged Bitcoin",
      "symbol": "BTCB",
      "address": "0x7130d2A12B9BCbFAe4f2634d864A1Ee1Ce3Ead9c",
      "chainId": 56,
      "decimals": 18,
      "logoURI": "https://tokens.pancakeswap.finance/images/0x7130d2A12B9BCbFAe4f2634d864A1Ee1Ce3Ead9c.png"
    },
    {
      "name": "Binance Pegged BUSD",
      "symbol": "BUSD",
      "address": "0xe9e7CEA3DedcA5984780Bafc599bD69ADd087D56",
      "chainId": 56,
      "decimals": 18,
      "logoURI": "https://tokens.pancakeswap.finance/images/0xe9e7CEA3DedcA5984780Bafc599bD69ADd087D56.png"
    },
    {
      "name": "Binance Pegged USDT",
      "symbol": "USDT",
      "address": "0x55d398326f99059fF775485246999027B3197955",
      "chainId": 56,
      "decimals": 18,
      "logoURI": "https://tokens.pancakeswap.finance/images/0x55d398326f99059fF775485246999027B3197955.png"
    },
    {
      "name": "Binance Pegged USD Coin",
      "symbol": "USDC",
      "address": "0x8AC76a51cc950d9822D68b83fE1Ad97B32Cd580d",
      "chainId": 56,
      "decimals": 18,
      "logoURI": "https://tokens.pancakeswap.finance/images/0x8AC76a51cc950d9822D68b83fE1Ad97B32Cd580d.png"
    },
    {
      "name": "ARB",
      "symbol": "Arbitrum",
      "address": "0xa050FFb3eEb8200eEB7F61ce34FF644420FD3522",
      "chainId": 56,
      "decimals": 18,
      "logoURI": "https://tokens.pancakeswap.finance/images/0xa050FFb3eEb8200eEB7F61ce34FF644420FD3522.png"
    },
    {
      "name": "Optimism",
      "symbol": "OP",
      "address": "0x170C84E3b1D282f9628229836086716141995200",
      "chainId": 56,
      "decimals": 18,
      "logoURI": "https://tokens.pancakeswap.finance/images/0x170C84E3b1D282f9628229836086716141995200.png"
    }
  ]
}
